#!/usr/bin/env bash
set -e

INSTALL_DIR="$HOME/.zdots"

echo "🔧 Setting up zdots in $INSTALL_DIR..."

# ─────────────────────────────────────────────
# 🧠 Ensure Zsh is installed and set as default
# ─────────────────────────────────────────────
if ! command -v zsh &> /dev/null; then
  echo "⚠️ Zsh is not installed."
  read -p "Would you like to install Zsh and set it as your default shell? (Y/n): " install_zsh
  if [[ "$install_zsh" =~ ^[Yy]$ ]]; then
    sudo pacman -S zsh
    chsh -s "$(which zsh)"
    echo "✅ Zsh installed and set as default shell."
  else
    echo "❌ Zsh is required for this setup. Exiting."
    exit 1
  fi
fi

# ─────────────────────────────────────────────
# 📦 Package check and summary
# ─────────────────────────────────────────────
export PATH="$HOME/.cargo/bin:$PATH"

tools=(
  bat
  eza
  fzf
  p7zip
  starship
  unrar
  unzip
  zoxide
)

installed=()
missing=()

echo "🔍 Checking required tools..."
for tool in "${tools[@]}"; do
  if command -v "$tool" &> /dev/null; then
    installed+=("$tool")
  else
    missing+=("$tool")
  fi
done

echo ""
echo "✅ Already installed: ${installed[*]:-"None"}"
echo "📦 Missing and will be installed: ${missing[*]:-"None"}"

if [[ ${#missing[@]} -eq 0 ]]; then
  echo "🎉 All required tools are already installed. Skipping package install."
else
  echo ""
  read -p "Proceed with installing missing packages via pacman? (Y/n): " confirm
  if [[ "$confirm" =~ ^[Yy]$ ]]; then
    for pkg in "${missing[@]}"; do
      echo "📦 Installing $pkg..."
      sudo pacman -S --noconfirm "$pkg"
    done
  else
    echo "⏭️ Skipping package installation. You may encounter issues if required tools are missing."
  fi
fi

# ─────────────────────────────────────────────
# 🗄 Backup existing .zshrc before replacing
# ─────────────────────────────────────────────
backup_file=""
if [[ -f "$HOME/.zshrc" && ! -L "$HOME/.zshrc" ]]; then
  backup_file="$HOME/.zshrc.bak.$(date +%Y%m%d%H%M%S)"
  echo "🗄 Backing up existing .zshrc to $backup_file"
  mv "$HOME/.zshrc" "$backup_file"
fi

# ─────────────────────────────────────────────
# 🏗 Build flattened .zshrc from modular files
# ─────────────────────────────────────────────
echo "🛠 Generating monolithic ~/.zshrc from zdots modules..."
{
  echo "# ==================================================================="
  echo "# Generated by Zdots setup on $(date)"
  echo "# Edit this file directly for changes."
  echo "# ==================================================================="
  echo ""
  echo "# History Configuration"
  echo "HISTFILE=~/.zsh_history"
  echo "HISTSIZE=9023"
  echo "SAVEHIST=9023"
  echo ""
  cat "$INSTALL_DIR/zsh/options.zsh"
  echo ""
  cat "$INSTALL_DIR/zsh/aliases.zsh"
  echo ""
  cat "$INSTALL_DIR/zsh/functions.zsh"
  echo ""
  cat "$INSTALL_DIR/zsh/plugins.zsh"
  echo ""
  cat "$INSTALL_DIR/zsh/prompt.zsh"
  echo ""
  echo "# Test your setup by uncommenting the following lines:"
  echo "# zmodload zsh/zprof"
  echo "# zprof"
} > "$HOME/.zshrc"

# ─────────────────────────────────────────────
# 🔄 Merge aliases, exports, functions from backup
# ─────────────────────────────────────────────
if [[ -n "$backup_file" && -f "$backup_file" ]]; then
  echo "🔄 Merging settings from $backup_file into new ~/.zshrc..."

  {
    echo ""
    echo "# -------------------------------------------------------------------"
    echo "# Imported from previous .zshrc backup on $(date)"
    echo "# -------------------------------------------------------------------"
  } >> "$HOME/.zshrc"

  # Aliases
  grep -E '^alias ' "$backup_file" | while read -r line; do
    grep -Fxq "$line" "$HOME/.zshrc" || echo "$line" >> "$HOME/.zshrc"
  done

  # All exports
  grep -E '^export ' "$backup_file" | while read -r line; do
    grep -Fxq "$line" "$HOME/.zshrc" || echo "$line" >> "$HOME/.zshrc"
  done

  # PATH modifications without export
  grep -E '^PATH=' "$backup_file" | while read -r line; do
    grep -Fxq "$line" "$HOME/.zshrc" || echo "$line" >> "$HOME/.zshrc"
  done

  # Multi-line functions
  awk '
    /^function [a-zA-Z0-9_]+\s*\(\)\s*\{/ {infunc=1; fn=$0 ORS; next}
    infunc {fn=fn $0 ORS; if (/^\}/) {print fn; infunc=0}}
  ' "$backup_file" | while read -r block; do
    grep -Fq "$block" "$HOME/.zshrc" || echo -e "$block" >> "$HOME/.zshrc"
  done

  echo "✅ Merge complete."
fi

echo ""
echo "✅ Zdots Setup complete. Reload your shell with: source ~/.zshrc"
